set(CMAKE_INSTALL_PREFIX ./)

# fftw
install(FILES ${FFTW_DYNLIBS} CONFIGURATIONS DESTINATION ${CMAKE_INSTALL_PREFIX})

# glfw
install(FILES ${GLFW_DYNLIBS} DESTINATION ${CMAKE_INSTALL_PREFIX})

# builtin resources
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/BuiltinResources DESTINATION ${CMAKE_INSTALL_PREFIX})