
if (CMAKE_BUILD_TYPE MATCHES "Debug")
	set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/Debug)
else()
	set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/Release)
endif()

# fftw
install(FILES ${FFTW_DYNLIBS} CONFIGURATIONS DESTINATION ${CMAKE_INSTALL_PREFIX})

# glfw
install(FILES ${GLFW_DYNLIBS} DESTINATION ${CMAKE_INSTALL_PREFIX})