set(MAIN_SRC
	Source/main.cpp
)

file(GLOB_RECURSE CORE_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Core/*.cpp)

file(GLOB_RECURSE DATAS_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Datas/*.cpp)

file(GLOB_RECURSE UI_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/UI/*.cpp)

file(GLOB_RECURSE MATH_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Math/*.cpp)

file(GLOB_RECURSE IMPORTERS_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Importers/*.cpp)

file(GLOB_RECURSE RENDERER_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Renderer/*.cpp)

file(GLOB_RECURSE RENDER_RESOURCES_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/RenderResources/*.cpp)

file(GLOB_RECURSE SCENE_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Scene/*.cpp)

set(EFFECTS_SRC
		${MAIN_SRC}
		${CORE_SRC}
		${DATAS_SRC}
		${UI_SRC}
		${MATH_SRC}
		${IMPORTERS_SRC}
		${RENDERER_SRC}
		${RENDER_RESOURCES_SRC}
		${SCENE_SRC})