set(MAIN_SRC
	Source/main.cpp
)

file(GLOB_RECURSE CORE_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Core/*.cpp)

file(GLOB_RECURSE DATAS_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Datas/*.cpp)

file(GLOB_RECURSE UI_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/UI/*.cpp)

file(GLOB_RECURSE MATH_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Math/*.cpp)

file(GLOB_RECURSE IMPORTERS_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Importers/*.cpp)

file(GLOB_RECURSE RENDERER_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Renderer/*.cpp)

file(GLOB_RECURSE EDITOR_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Editor/*.cpp)

file(GLOB_RECURSE RESOURCE_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Resource/*.cpp)

file(GLOB_RECURSE SCENE_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/Scene/*.cpp)

file(GLOB_RECURSE GAME_PLAY_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/GamePlay/*.cpp)

set(EFFECTS_SRC
		${MAIN_SRC}
		${CORE_SRC}
		${DATAS_SRC}
		${UI_SRC}
		${MATH_SRC}
		${IMPORTERS_SRC}
		${EDITOR_SRC}
		${RENDERER_SRC}
		${RESOURCE_SRC}
		${SCENE_SRC}
		${GAME_PLAY_SRC})